#!/bin/bash
if which swiftlint >/dev/null; then
	swiftlint autocorrect --config tools/format/.swiftlint.yml
	git diff --cached --name-only --diff-filter=d | while read filename; do git add "$filename"; done
else
	echo "warning: SwiftLint not installed, please run 'make install-swiftlint'"
fi
