line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    ignores_interpolated_strings: true
function_body_length:
    warning: 100
    error: 150
type_body_length:
    warning: 500
    error: 1000
file_length:
    warning: 1200
    error: 1500
    ignore_comment_only_lines: true
