disabled_rules: # rule identifiers to exclude from running
- nesting
opt_in_rules: # some rules are opt-in only
- closure_end_indentation
- convenience_type
- empty_collection_literal
- empty_count
- empty_string
- force_unwrapping
- missing_docs
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- operator_usage_whitespace
- sorted_imports
- toggle_bool
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
excluded: # paths to ignore during linting
- Carthage
- TestApps/*/Pods
- TestApps/*/libs
- Pods
- Documentation

analyzer_rules:
- unused_import

empty_count: 
    severity: warning
force_cast: warning
force_try: warning
identifier_name:
    allowed_symbols: "_"
    excluded:
        - id
        - no
        - ok
line_length:
    warning: 180
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 50
    error: 150
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
