# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'AEPDemoApp'
project 'AEPDemoApp'

target 'AEPDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AEPDemoApp
  #pod 'ACPCore', '~> 2.0'
  #pod 'ACPGriffon', '~> 1.0'
  #pod 'ACPExperiencePlatform', :path => '~/git/mobile/experience-platform/public/platform-extension-ios'
  pod 'ACPExperiencePlatform', :git => 'https://github.com/kevinlind/platform-extension-ios', :branch => 'amsdk-9772-ci-publish'

end
