# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'AEPCommerceDemoApp'
project 'AEPCommerceDemoApp.xcodeproj'

target 'AEPCommerceDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AEPEdge', :path => '../../'
  pod 'AEPCore', :git => 'https://github.com/adobe/aepsdk-core-ios.git', :branch => 'dev-v3.1.0'
  pod 'AEPEdgeIdentity', :git => 'git@github.com:adobe/aepsdk-edgeidentity-ios.git', :branch => 'dev'
  pod 'ACPCore', :git => 'https://github.com/adobe/aep-sdk-compatibility-ios.git', :branch => 'main'
  pod 'AEPAssurance'

end
