# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'AEPCommerceDemoApp'
project 'AEPCommerceDemoApp.xcodeproj'

target 'AEPCommerceDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AEPEdge', :path => '../../'
  pod 'AEPCore', :git => 'https://github.com/adobe/aepsdk-core-ios', :branch => 'staging'
  pod 'AEPServices', :git => 'https://github.com/adobe/aepsdk-core-ios', :branch => 'staging'
  pod 'AEPEdgeIdentity'
  pod 'AEPAssurance'

end
