# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'AEPCommerceDemoApp'
project 'AEPCommerceDemoApp.xcodeproj'

target 'AEPCommerceDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AEPExperiencePlatform', :git => 'git@github.com:emdobrin/aepsdk-platform-ios.git', :branch => 'AMSDK-10474'
  pod 'AEPCore', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPServices', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'SwiftRulesEngine', :git => 'git@github.com:adobe/aepsdk-rulesengine-ios.git', :branch => 'dev'
  pod 'AEPLifecycle', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  pod 'AEPIdentity', :git => 'git@github.com:adobe/aepsdk-core-ios.git', :branch => 'main'
  
  pod 'ACPGriffon', '1.1.3'

end
