disabled_rules: # rule identifiers to exclude from running
- nesting
- mark
opt_in_rules: # some rules are opt-in only
- closure_end_indentation
- convenience_type
- empty_collection_literal
- empty_count
- empty_string
- force_unwrapping
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- operator_usage_whitespace
- sorted_imports
- toggle_bool
- unneeded_parentheses_in_closure_argument
- unused_import
- vertical_parameter_alignment_on_call
included: # paths to include. '--path' is ignored
- code/src
- demo/AEPCommerceDemoApp
excluded: # paths to ignore during linting
- Carthage
- demo/*/Pods
- demo/*/xdmlib
- demo/*/libs

empty_count: 
    severity: warning
force_cast: warning
force_try: warning
identifier_name:
    excluded:
        - id
        - no
        - ok
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 50
    error: 150
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"

anyobject_protocol:
    severity: error
closing_brace:
    severity: error
closure_end_indentation:
    severity: error
closure_spacing:
    severity: error
colon:
    severity: error
comma:
    severity: error
control_statement:
    severity: error
empty_enum_arguments:
    severity: error
empty_parameters:
    severity: error
empty_parentheses_with_trailing_closure:
    severity: error
explicit_init:
    severity: error
explicit_self:
    severity: error
implicit_return:
    severity: error
joined_default_parameter:
    severity: error
leading_whitespace:
    severity: error
legacy_cggeometry_functions:
    severity: error
legacy_constant:
    severity: error
legacy_constructor:
    severity: error
legacy_nsgeometry_functions:
    severity: error
literal_expression_end_indentation:
    severity: error
mark:
    severity: error
modifier_order:
    severity: error
nimble_operator:
    severity: error
no_space_in_method_call:
    severity: error
number_separator: 
    severity: error
opening_brace: 
    severity: error
operator_usage_whitespace:
    severity: error
optional_enum_case_matching:
    severity: error
prefer_self_type_over_type_of_self:
    severity: error
private_over_fileprivate:
    severity: error
protocol_property_accessors_order:
    severity: error
redundant_discardable_let:
    severity: error
redundant_nil_coalescing:
    severity: error
redundant_objc_attribute:
    severity: error
redundant_optional_initialization:
    severity: error
redundant_type_annotation:
    severity: error
redundant_void_return:
    severity: error
return_arrow_whitespace:
    severity: error
sorted_imports:
    severity: error
statement_position:
    severity: error
syntactic_sugar:
    severity: error
toggle_bool: 
    severity: error
trailing_comma:
    severity: error
trailing_newline:
    severity: error
trailing_semicolon:
    severity: error
trailing_whitespace:
    severity: error
unneeded_parentheses_in_closure_argument:
    severity: error
untyped_error_in_catch:
    severity: error
unused_closure_parameter:
    severity: error
unused_control_flow_label:
    severity: error
unused_import:
    severity: error
vertical_whitespace:
    severity: error
vertical_whitespace_between_cases:
    severity: error
vertical_whitespace_closing_braces:
    severity: error
vertical_whitespace_opening_braces:
    severity: error
xct_specific_matcher:
    severity: error
yoda_condition: 
    severity: error
