name: Build and Test

on:
  pull_request:

jobs:
  build-and-test:
    name: " "
    uses: timkimadobe/aepsdk-commons/.github/workflows/ios-build-and-test.yml@gha-ios-5.0.0
    with:
      ios-device-names: '["iPhone 15"]'
      ios-versions: '["18.1"]'
      tvos-device-names: '["Apple TV"]'
      tvos-versions: '["18.1"]'
      run-test-ios-unit: true
      run-test-ios-functional: true
      run-test-ios-integration: true
      run-test-tvos-unit: true
      run-test-tvos-functional: true
      run-build-xcframework-and-app: true
    secrets: inherit