# Remote action to execute E2E functional tests

name: E2E Integration Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use when running integration tests'
        required: false
        default: 'main'
      id:
        description: 'Identifier for the run'
        required: false
      environment:
        description: 'Konductor environment to test (prod, pre-prod, int)'
        required: true
        default: 'prod'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  functional-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: ${{ github.event.inputs.id }}
      run: echo Run Identifier is ${{ inputs.id }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Cache Cocoapods
      uses: actions/cache@v3
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Install Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 5G


    # Update the plist file which controls the environment used by the e2e tests
    - name: Update environment
      run: make set-e2e-environment ENV=${{ github.event.inputs.environment }}

    # Runs a single command using the runners shell
    - name: Execute functional tests
      run: make e2e-functional-test
