name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/version (ex: 5.0.1)'
        required: true
        default: '1.0.0'

      run_full_release:
        description: 'Run full release process ("no" to skip)'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

      release_pod:
        description: 'Release to Cocoapods'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  release:
    uses: adobe/aepsdk-testutils-ios/.github/workflows/reusable_release.yml@test-reusable-workflows
    with:
      tag: ${{ github.event.inputs.tag }}
      run_full_release: ${{ github.event.inputs.run_full_release }}
      release_pod: ${{ github.event.inputs.release_pod }}
      library_name: AEPEdge
    secrets: inherit
