on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to use for the extension. Example: 1.5.2'
        required: true

      branch:
        description: 'Branch to be used when updating versions'
        required: true

      core-dependency:
        description: 'If a version is provided, update AEPCore dependency in podspec and Package.swift'
        required: false

      edge-identity-dependency:
        description: 'If a version is provided, update AEPEdgeIdentity dependency in podspec and Package.swift'
        required: false

jobs:
  call-reusable-workflow:
    uses: adobe/aepsdk-testutils-ios/.github/workflows/reusable_update_versions.yml@test-reusable-workflows
    with:
      version: ${{ github.event.inputs.version }}
      branch: ${{ github.event.inputs.branch }}
      libraries: |
        Edge:AEPCore ${{ github.event.inputs.core-dependency }}, AEPEdgeIdentity ${{ github.event.inputs.edge-identity-dependency }};
